---
- name: ansible playbook to copy file
  hosts: all
  become: true
  tasks:
  - name: copy a file
    copy:
      src: /opt/ansible/index.html
      dest: /home/eechukwu
      mode: 0600
      owner: kene
