---
- name: this playbook install apache2 to ubuntu server
  hosts: dbservers
  become: true
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present

  - name: start apache2 service on ubuntu
    service:
      name: apache2
      state: started
