---
- name: this playbook install apache2 or httpd depending on system
  hosts: all
  become: true 
  tasks:
  
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: install_apache

  - name: start apache2 service on ubuntu
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    tags: start_apache

  - name: install httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
    tags: install_apache
    ignore_errors: yes
    
  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    tags: start_apache

  - name: copy index.html file
    copy: 
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

